---
- name: setup Mysql with medium_db db and remote login
  become: yes
  hosts: ans4

  vars:
    mysql_root_password: "rootpassword"  # Cambia esto por tu contraseña deseada para root
    db_user: "user"
    db_pass: "pass"  # Cambia esto por tu contraseña deseada para el nuevo usuario
    db_name: "dbname"

  tasks:
    - name: Installing Mysql and dependencies
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - mysql-server
        - mysql-client
        - python3-mysqldb
        - libmysqlclient-dev

    - name: start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Set root password for MySQL
      mysql_user:
        name: root
        host: localhost
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present

    - name: Remove the anonymous MySQL user
      mysql_user:
        name: ''
        host: localhost
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Remove the MySQL test database
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: creating mysql user
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        priv: '*.*:ALL'
        host: '%'
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: creating zabbix DB
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Enable remote login to mysql
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes
      notify:
        - Restart mysql

  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted
